# Mathematical functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [3]:
x = np.array([0., 1., 30, 90])
sine = np.sin(x)
cosine = np.cos(x)
tangent = np.tan(x)
print(f"sine: {sine}")
print(f"cosine: {cosine}")
print(f"tangent: {tangent}")

sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041]


Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [5]:
x = np.array([-1., 0, 1.])
inverse_sine = np.arcsin(x)
inverse_cosine = np.arccos(x)
inverse_tangent= np.arctan(x)
print(f"inverse sine: {inverse_sine}")
print(f"inverse cosine: {inverse_cosine}")
print(f"inverse tangent: {inverse_tangent}")

inverse sine: [-1.57079633  0.          1.57079633]
inverse cosine: [3.14159265 1.57079633 0.        ]
inverse tangent: [-0.78539816  0.          0.78539816]


Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [8]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.degrees(x)

array([-180.,  -90.,   90.,  180.])

Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [13]:
x = np.array([-180.,  -90.,   90.,  180.])
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [14]:
x = np.array([-1., 0, 1.])
x_1 = np.sinh(x)
x_2 = np.cosh(x)
x_3 = np.tanh(x)
print(x_1)
print(x_2)
print(x_3)

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [17]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
y_1 = np.around(x)
y_2 = np.floor(x)
y_3 = np.ceil(x)
y_4 = np.trunc(x)
print(y_1)
print(y_2)
print(y_3)
print(y_4)

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]


## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [19]:
x = np.array([1, 2, 4, 7, 0])
x_1 = np.diff(x)
print(x_1)

[ 1  2  3 -7]


Return the cross product of x and y.  
Hint: use np.cross()

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.cross(x, y)
print(z)

[-3  6 -3]


## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [22]:
x = np.array([1., 2., 3.], np.float32)
y = np.exp(x)
print(y)

[ 2.7182817  7.389056  20.085537 ]


Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [23]:
x = np.array([1., 2., 3.], np.float32)
y = np.expm1(x)
print(y)

[ 1.7182817  6.389056  19.085537 ]


Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [24]:
x = np.array([1., 2., 3.], np.float32)
y = np.exp2(x)
print(y)

[2. 4. 8.]


Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [25]:
x = np.array([1, np.e, np.e**2])
natural_log = np.log(x)
common_log = np.log10(x)
base_2_log = np.log2(x)
print(f"natural log = {natural_log}")
print(f"common log = {common_log}")
print(f"base 2 log = {base_2_log}")

natural log = [0. 1. 2.]
common log = [0.         0.43429448 0.86858896]
base 2 log = [0.         1.44269504 2.88539008]


## Arithmetic operations

Add x and y element-wise.

In [28]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
z = np.add(x, y)
print(z)

[0 0 0]


Subtract y from x element-wise.

In [29]:
x = np.array([3, 4, 5])
y = np.array(3)
z = np.subtract(x, y)
print(z)

[0 1 2]


Multiply x by y element-wise.

In [30]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
z = np.multiply(x, y)
print(z)

[ 3  0 -5]


Divide x by y element-wise

In [31]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
z = np.divide(x, y)
print(z)

[3.         2.         1.66666667]


Compute numerical negative value of x, element-wise.

In [32]:
x = np.array([1, -1])
x_1 = np.negative(x)
print(x_1)

[-1  1]


Compute the reciprocal of x, element-wise.

In [34]:
x = np.array([1., 2., .2])
x_1 = np.reciprocal(x)
print(x_1)

[1.  0.5 5. ]


Compute $x^y$, element-wise.

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
z = x**y
print(z)

[[ 1  4]
 [ 3 16]]


Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [37]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
z = np.mod(x, y)
print(z)

[1 0 1 1 0 1]


## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [38]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x = np.arange(10)
x_1 = np.where(x > 7, 7)
print(x_1)

ValueError: either both or neither of x and y should be given

Compute the square of x, element-wise.

In [49]:
x = np.array([1, 2, -1])
x_1 = np.square(x)
print(x_1)

[1 4 1]


Compute square root of x element-wise.

In [50]:
x = np.array([1., 4., 9.])
x_1 = np.sqrt(x)
print(x_1)

[1. 2. 3.]


Compute the absolute value of x.

In [51]:
x = np.array([[1, -1], [3, -3]])
x_1 = np.abs(x)
print(x_1)

[[1 1]
 [3 3]]


Compute an element-wise indication of the sign of x, element-wise.

In [27]:
x = np.array([1, 3, 0, -1, -3])

[ 1  1  0 -1 -1]
