# Mathematical functions

In [1]:
import numpy as np

In [2]:
import math

In [2]:
np.__version__

'1.19.2'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [26]:
x = np.array([0., 1., 30, 90])
sin=np.sin(x)
cos = np.cos(x)
tan = np.cos(x)
print(f"sin :{sin}")
print(f"cos :{cos}")
print(f"tan :{tan}")

sin :[ 0.          0.84147098 -0.98803162  0.89399666]
cos :[ 1.          0.54030231  0.15425145 -0.44807362]
tan :[ 1.          0.54030231  0.15425145 -0.44807362]


Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [27]:
x = np.array([-1., 0, 1.])
arcsin = np.arcsin(x)
arccos = np.arccos(x)
arctan = np.arccos(x)
print(f"inverse sin :{arcsin}")
print(f"inverse cos :{arccos}")
print(f"inverse tan :{arctan}")

inverse sin :[-1.57079633  0.          1.57079633]
inverse cos :[3.14159265 1.57079633 0.        ]
inverse tan :[3.14159265 1.57079633 0.        ]


Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [28]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
np.degrees(x)

array([-180.,  -90.,   90.,  180.])

Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [32]:
x = np.array([-180.,  -90.,   90.,  180.])
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [7]:
x = np.array([-1., 0, 1.])
print(math.sinh(x))
print(math.cosh(x))
print(math.tanh(x))

TypeError: only size-1 arrays can be converted to Python scalars

## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [13]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
np.around(x)

array([ 2.,  2.,  2.,  3., -2., -2., -3.])

## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [11]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

Return the cross product of x and y.  
Hint: use np.cross()

In [15]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x,y)

array([-3,  6, -3])

## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [17]:
x = np.array([1., 2., 3.], np.float32)
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [18]:
x = np.array([1., 2., 3.], np.float32)
np.expm1(x)

array([ 1.7182817,  6.389056 , 19.085537 ], dtype=float32)

Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [19]:
x = np.array([1., 2., 3.], np.float32)
np.exp2(x)

array([2., 4., 8.], dtype=float32)

Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [24]:
x = np.array([1, np.e, np.e**2])
np.log(x)

array([0., 1., 2.])

## Arithmetic operations

Add x and y element-wise.

In [15]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])


[0 0 0]


Subtract y from x element-wise.

In [25]:
x = np.array([3, 4, 5])
y = np.array(3)
x-y

array([0, 1, 2])

Multiply x by y element-wise.

In [26]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
x*y

array([ 3,  0, -5])

Divide x by y element-wise

In [27]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
x/y

array([3.        , 2.        , 1.66666667])

Compute numerical negative value of x, element-wise.

In [28]:
x = np.array([1, -1])
x*-1

array([-1,  1])

Compute the reciprocal of x, element-wise.

In [20]:
x = np.array([1., 2., .2])

[1.  0.5 5. ]


Compute $x^y$, element-wise.

In [29]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
x**y

array([[ 1,  4],
       [ 3, 16]], dtype=int32)

Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [34]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print(x%y)
np.mod(x,y)

[1 0 1 1 0 1]


array([1, 0, 1, 1, 0, 1], dtype=int32)

## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [40]:
x = np.arange(10)
np.where(x<3, 3,np.where(x>7,7,x))

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

Compute the square of x, element-wise.

In [41]:
x = np.array([1, 2, -1])
x**2

array([1, 4, 1], dtype=int32)

Compute square root of x element-wise.

In [3]:
x = np.array([1., 4., 9.])
np.sqrt(x)

array([1., 2., 3.])

Compute the absolute value of x.

In [4]:
x = np.array([[1, -1], [3, -3]])
np.absolute(x)

array([[1, 1],
       [3, 3]])

Compute an element-wise indication of the sign of x, element-wise.

In [27]:
x = np.array([1, 3, 0, -1, -3])

[ 1  1  0 -1 -1]
