# Mathematical functions

In [2]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

## Trigonometric functions

Calculate sine, cosine, and tangent of x, element-wise.  
Hint: use np.sin(), np.cos(), np.tan()

In [4]:
x = np.array([0., 1., 30, 90])

In [5]:
np.sin(x)

array([ 0.        ,  0.84147098, -0.98803162,  0.89399666])

In [6]:
np.cos(x)

array([ 1.        ,  0.54030231,  0.15425145, -0.44807362])

In [7]:
np.tan(x)

array([ 0.        ,  1.55740772, -6.4053312 , -1.99520041])

Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.  
Hint: use np.arcsin(), np.arccos(), np.arctan()

In [9]:
x = np.array([-1., 0, 1.])

In [10]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [11]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [12]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

Convert angles from radians to degrees.  
Hint: use np.degrees() or np.rad2deg()

In [5]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

[-180.  -90.   90.  180.]


In [13]:
np.degrees(x)

array([-57.29577951,   0.        ,  57.29577951])

In [14]:
np.rad2deg(x)

array([-57.29577951,   0.        ,  57.29577951])

Convert angles from degrees to radians.  
Hint: use np.radians() or np.deg2rad()

In [16]:
x = np.array([-180.,  -90.,   90.,  180.])

In [18]:
np.radians(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

In [19]:
np.deg2rad(x)

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

## Hyperbolic functions

Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.  
Hint: use np.sinh(), np.cosh(), np.tanh()

In [21]:
x = np.array([-1., 0, 1.])

In [23]:
np.sinh(x)

array([-1.17520119,  0.        ,  1.17520119])

In [24]:
np.cosh(x)

array([1.54308063, 1.        , 1.54308063])

In [25]:
np.tanh(x)

array([-0.76159416,  0.        ,  0.76159416])

## Rounding

Round x element-wise  
Hint: use np.around(x) or np.floor(x) or np.ceil(x) or np.trunc(x)

In [8]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

[ 2.  2.  2.  3. -2. -2. -3.]
[ 2.  1.  2.  2. -3. -3. -3.]
[ 3.  2.  3.  3. -2. -2. -2.]
[ 2.  1.  2.  2. -2. -2. -2.]


In [26]:
np.around(x)

array([-1.,  0.,  1.])

In [27]:
np.floor(x)

array([-1.,  0.,  1.])

In [28]:
np.ceil(x)

array([-1.,  0.,  1.])

In [29]:
np.trunc(x)

array([-1.,  0.,  1.])

## Sums, products, differences

Calculate the difference between neighboring elements, element-wise.  
Hint: use np.diff()

In [31]:
x = np.array([1, 2, 4, 7, 0])

In [33]:
np.diff(x)

array([ 1,  2,  3, -7])

In [34]:
np.sum(x)

14

In [37]:
np.product(x)

0

Return the cross product of x and y.  
Hint: use np.cross()

In [39]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [41]:
np.cross(x, y)

array([-3,  6, -3])

## Exponents and logarithms

Compute $e^x$, element-wise.  
Hint: use np.exp()

In [43]:
x = np.array([1., 2., 3.], np.float32)

In [45]:
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Calculate exp(x) - 1 for all elements in x.  
Hint: there are np.expm1() and np.exp(), make your own choice and use it properly

In [12]:
x = np.array([1., 2., 3.], np.float32)

[ 1.7182817  6.389056  19.085537 ]


In [46]:
np.expm1(x)

array([ 1.7182817,  6.389056 , 19.085537 ], dtype=float32)

In [47]:
np.exp(x)

array([ 2.7182817,  7.389056 , 20.085537 ], dtype=float32)

Calculate $2^p$ for all p in x.  
Hint: Refer to the lecture. np.exp2() will help, too.

In [13]:
x = np.array([1., 2., 3.], np.float32)

[2. 4. 8.]


In [48]:
np.exp2(x)

array([2., 4., 8.], dtype=float32)

Compute natural, base 10, and base 2 logarithms of x element-wise.  
Hint: use np.log(), np.log10(), np.log2()

In [14]:
x = np.array([1, np.e, np.e**2])

natural log = [0. 1. 2.]
common log = [0.         0.43429448 0.86858896]
base 2 log = [0.         1.44269504 2.88539008]


In [49]:
np.log(x)

array([0.       , 0.6931472, 1.0986123], dtype=float32)

In [50]:
np.log10(x)

array([0.        , 0.30103   , 0.47712126], dtype=float32)

In [51]:
np.log2(x)

array([0.       , 1.       , 1.5849625], dtype=float32)

## Arithmetic operations

Add x and y element-wise.

In [53]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])

In [64]:
x+y

array([4., 6., 8.])

Subtract y from x element-wise.

In [56]:
x = np.array([3, 4, 5])
y = np.array(3)

In [65]:
x-y

array([2., 2., 2.])

Multiply x by y element-wise.

In [58]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])

In [66]:
x*y

array([ 3.,  8., 15.])

Divide x by y element-wise

In [60]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])

In [63]:
x/y

array([3.        , 2.        , 1.66666667])

Compute numerical negative value of x, element-wise.

In [71]:
x = np.array([1, -1])

In [72]:
np.negative(x)

array([-1,  1])

Compute the reciprocal of x, element-wise.

In [74]:
x = np.array([1., 2., .2])

In [75]:
np.reciprocal(x)

array([1. , 0.5, 5. ])

Compute $x^y$, element-wise.

In [77]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

In [78]:
x**y

array([[ 1,  4],
       [ 3, 16]], dtype=int32)

Compute the remainder of x / y element-wise in two different ways.  
Hint: use np.mod() or `%` operator

In [80]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2

In [81]:
np.mod(x, y)

array([1, 0, 1, 1, 0, 1], dtype=int32)

In [82]:
x%y

array([1, 0, 1, 1, 0, 1], dtype=int32)

## Miscellaneous

If an element of x is smaller than 3, replace it with 3.  
And if an element of x is bigger than 7, replace it with 7.  
Hint: use array masking

In [87]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.where(x < 5, '3', np.where(x > 7, '7', x))

array(['3', '3', '3', '3', '3', '5', '6', '7', '7', '7'], dtype='<U11')

Compute the square of x, element-wise.

In [92]:
x = np.array([1, 2, -1])

In [93]:
x**2

array([1, 4, 1], dtype=int32)

Compute square root of x element-wise.

In [95]:
x = np.array([1., 4., 9.])

In [96]:
np.sqrt(x)

array([1., 2., 3.])

Compute the absolute value of x.

In [98]:
x = np.array([[1, -1], [3, -3]])

In [99]:
np.absolute(x)

array([[1, 1],
       [3, 3]])

Compute an element-wise indication of the sign of x, element-wise.

In [101]:
x = np.array([1, 3, 0, -1, -3])

In [103]:
np.sign(x)

array([ 1,  1,  0, -1, -1])